-- Creacion de tablas
create table caballos (id bigint generated by default as identity, altura_metros float not null, color_pelo varchar(80) not null, fecha_nacimiento timestamp not null, identificacion varchar(80) not null, nombre varchar(80) not null, sexo varchar(80) not null, dueno_id bigint not null, espacio_id bigint not null, primary key (id));
create table ciudades (id bigint generated by default as identity, nombre varchar(80) not null, pais_id bigint not null, primary key (id));
create table cuidados_extra (id bigint generated by default as identity, descripcion varchar(255) not null, caballo_id bigint not null, primary key (id));
create table direcciones (id bigint generated by default as identity, calle varchar(80) not null, numero integer not null, ciudad_id bigint not null, dueno_id bigint not null, primary key (id));
create table duenos (id bigint generated by default as identity, apellidos varchar(80) not null, email varchar(80) not null, nombres varchar(80) not null, telefono varchar(13) not null, primary key (id));
create table espacios (id bigint generated by default as identity, localizacion varchar(80) not null, nombre varchar(80) not null, tipo_id bigint not null, primary key (id));
create table paises (id bigint generated by default as identity, nombre varchar(80) not null, primary key (id));
create table tipos (id bigint generated by default as identity, descripcion varchar(80) not null, primary key (id));
create table usuarios (id bigint generated by default as identity, apellidos varchar(80) not null, email varchar(80) not null, enabled boolean not null, nombres varchar(80) not null, password varchar(80) not null, username varchar(80) not null, primary key (id));
-- Condiciones en schema
alter table espacios add constraint UK_b84u15a9dgyfnq85jmijng2m0 unique (nombre);
alter table caballos add constraint FK2uii108w6h775hd7blq6em957 foreign key (dueno_id) references duenos;
alter table caballos add constraint FKhhgw1lsvvly5lhqmb8mspe9w foreign key (espacio_id) references espacios;
alter table ciudades add constraint FK4p6rph0gj1s70nntpch75tob4 foreign key (pais_id) references paises;
alter table cuidados_extra add constraint FKr2ripcfvou4rer3uq6fkh17v7 foreign key (caballo_id) references caballos;
alter table direcciones add constraint FK2v221eyetogmaqm4olx4pj4lj foreign key (ciudad_id) references ciudades;
alter table direcciones add constraint FK6mnnd3llp3ko15q8s0hp4g17f foreign key (dueno_id) references duenos;
alter table espacios add constraint FKr2oiyhuss2bqh8mjiohxpxt80 foreign key (tipo_id) references tipos;
